ERROR - 2024-03-24 12:27:15 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'swe2', 3306, '', 0)
#1 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\cig4ebook\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\xampp\htdocs\cig4ebook\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\cig4ebook\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\cig4ebook\app\Controllers\Books.php(35): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(941): App\Controllers\Books->addBook()
#10 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\cig4ebook\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\cig4ebook\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#3 C:\xampp\htdocs\cig4ebook\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\cig4ebook\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\cig4ebook\app\Controllers\Books.php(35): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(941): App\Controllers\Books->addBook()
#9 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\cig4ebook\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-03-24 12:27:15 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`title`, `category`, `isbn`, `author`, `cover_image`, `book_file`) VALUES (:title:, :category:, :isbn:, :author:, :cover_image:, :book_file:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Books.php(35): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->addBook()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-24 12:43:18 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'swe2', 3306, '', 0)
#1 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\cig4ebook\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\xampp\htdocs\cig4ebook\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\cig4ebook\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\cig4ebook\app\Controllers\Books.php(35): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(941): App\Controllers\Books->addBook()
#10 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\cig4ebook\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\cig4ebook\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#3 C:\xampp\htdocs\cig4ebook\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\cig4ebook\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\cig4ebook\app\Controllers\Books.php(35): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(941): App\Controllers\Books->addBook()
#9 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\cig4ebook\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-03-24 12:43:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`title`, `category`, `isbn`, `author`, `cover_image`, `book_file`) VALUES (:title:, :category:, :isbn:, :author:, :cover_image:, :book_file:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Books.php(35): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->addBook()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-24 12:59:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'swe2', 3306, '', 0)
#1 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\cig4ebook\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\xampp\htdocs\cig4ebook\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\cig4ebook\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\cig4ebook\app\Controllers\Books.php(35): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(941): App\Controllers\Books->addBook()
#10 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\cig4ebook\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\cig4ebook\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#3 C:\xampp\htdocs\cig4ebook\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\cig4ebook\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\cig4ebook\app\Controllers\Books.php(35): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(941): App\Controllers\Books->addBook()
#9 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\cig4ebook\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-03-24 12:59:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`title`, `category`, `isbn`, `author`, `cover_image`, `book_file`) VALUES (:title:, :category:, :isbn:, :author:, :cover_image:, :book_file:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Books.php(35): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->addBook()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-24 13:01:40 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'swe2', 3306, '', 0)
#1 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\cig4ebook\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\xampp\htdocs\cig4ebook\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\cig4ebook\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\cig4ebook\app\Controllers\Books.php(35): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(941): App\Controllers\Books->addBook()
#10 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\cig4ebook\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\cig4ebook\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#3 C:\xampp\htdocs\cig4ebook\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\cig4ebook\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\cig4ebook\app\Controllers\Books.php(35): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(941): App\Controllers\Books->addBook()
#9 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\cig4ebook\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-03-24 13:01:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`title`, `category`, `isbn`, `author`, `cover_image`, `book_file`) VALUES (:title:, :category:, :isbn:, :author:, :cover_image:, :book_file:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Books.php(35): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->addBook()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-24 13:05:09 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'swe2', 3306, '', 0)
#1 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\cig4ebook\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\xampp\htdocs\cig4ebook\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\cig4ebook\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\cig4ebook\app\Controllers\Books.php(35): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(941): App\Controllers\Books->addBook()
#10 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\cig4ebook\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\cig4ebook\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#3 C:\xampp\htdocs\cig4ebook\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\cig4ebook\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\cig4ebook\app\Controllers\Books.php(35): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(941): App\Controllers\Books->addBook()
#9 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\cig4ebook\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-03-24 13:05:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`title`, `category`, `isbn`, `author`, `cover_image`, `book_file`) VALUES (:title:, :category:, :isbn:, :author:, :cover_image:, :book_file:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Books.php(35): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->addBook()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-24 13:05:47 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'swe2', 3306, '', 0)
#1 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\cig4ebook\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\xampp\htdocs\cig4ebook\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\cig4ebook\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\cig4ebook\app\Controllers\Books.php(35): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(941): App\Controllers\Books->addBook()
#10 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\cig4ebook\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\cig4ebook\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#3 C:\xampp\htdocs\cig4ebook\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\cig4ebook\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\cig4ebook\app\Controllers\Books.php(35): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(941): App\Controllers\Books->addBook()
#9 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\cig4ebook\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-03-24 13:05:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`title`, `category`, `isbn`, `author`, `cover_image`, `book_file`) VALUES (:title:, :category:, :isbn:, :author:, :cover_image:, :book_file:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Books.php(35): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->addBook()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-24 13:11:48 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', 'swe2', 3306, '', 0)
#1 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\cig4ebook\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\xampp\htdocs\cig4ebook\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\cig4ebook\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\cig4ebook\app\Controllers\Books.php(35): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(941): App\Controllers\Books->addBook()
#10 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\cig4ebook\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\cig4ebook\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\cig4ebook\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\cig4ebook\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#3 C:\xampp\htdocs\cig4ebook\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\cig4ebook\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\cig4ebook\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\cig4ebook\app\Controllers\Books.php(35): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(941): App\Controllers\Books->addBook()
#9 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 C:\xampp\htdocs\cig4ebook\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\cig4ebook\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-03-24 13:11:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`title`, `category`, `isbn`, `author`, `cover_image`, `book_file`) VALUES (:title:, :category:, :isbn:, :author:, :cover_image:, :book_file:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Books.php(35): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->addBook()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
